export default [
  {
    id: 1,
    slug: 'horoshaia_novost',
    category: null,
    activeFrom: '2020-12-09T16:09:53+00:00',
    title: 'Вход пользователя в Личный кабинет по приглашению из письма',
    metaTitle: 'Мета заголовок',
    description: 'Президент Российской академии наук',
    metaDescription: 'Безопасное описание',
    previewPicture: {
      src: '/i/comments/1.jpg',
    },
    detailPicture: null,
    ogVk: '/i/posts/example.jpg',
    ogFb: '/i/posts/example.jpg',
    content: `rxyearw7KiQ`,
  },
  {
    id: 2,
    slug: 'horoshaia_novost',
    category: null,
    activeFrom: '2020-12-09T16:09:53+00:00',
    title: 'Вход пользователя в Личный кабинет по приглашению из письма',
    metaTitle: 'Мета заголовок',
    description: 'Президент Российской академии наук',
    metaDescription: 'Безопасное описание',
    previewPicture: {
      src: '/i/comments/1.jpg',
    },
    detailPicture: null,
    ogVk: '/i/posts/example.jpg',
    ogFb: '/i/posts/example.jpg',
    content: `rxyearw7KiQ`,
  },
]
